version: '3'

services:
  data-service:
    build: ./data-service
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  react-service:
    build: ./react-service
    ports:
      - "4000:4000"
    depends_on:
      - data-service
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmqhost
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynetwork

  mail-service:
    build: ./mail-service
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork: