version: '3'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  data-service:
    build: ./data-service
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    networks:
      - mynetwork
  
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always
    networks:
      - mynetwork

  socket-service:
    build: ./socket-service
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  react-service:
    build: ./react-service
    ports:
      - "4000:4000"
    depends_on:
      - data-service
      - socket-service
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmqhost
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mynetwork

  mail-service:
    build: ./mail-service
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
